import { Emitter } from '@rocket.chat/emitter';
import type { IWebRTCProcessor, WebRTCInternalStateMap, WebRTCProcessorConfig, WebRTCProcessorEvents } from '../../../definition';
import type { ServiceStateValue } from '../../../definition/services/IServiceProcessor';
export declare class MediaCallWebRTCProcessor implements IWebRTCProcessor {
    private readonly config;
    readonly emitter: Emitter<WebRTCProcessorEvents>;
    private peer;
    private iceGatheringTimedOut;
    private localStream;
    private localMediaStream;
    private remoteStream;
    private remoteMediaStream;
    private iceGatheringWaiters;
    private inputTrack;
    private _muted;
    get muted(): boolean;
    private _held;
    get held(): boolean;
    private stopped;
    private iceCandidateCount;
    private addedEmptyTransceiver;
    private _audioLevelTracker;
    private _audioLevel;
    get audioLevel(): number;
    private _localAudioLevel;
    private initialization;
    get localAudioLevel(): number;
    private _dataChannel;
    private _remoteMute;
    private _dataChannelEnded;
    constructor(config: WebRTCProcessorConfig);
    getRemoteMediaStream(): MediaStream;
    setInputTrack(newInputTrack: MediaStreamTrack | null): Promise<void>;
    createOffer({ iceRestart }: {
        iceRestart?: boolean;
    }): Promise<RTCSessionDescriptionInit>;
    setMuted(muted: boolean): void;
    setHeld(held: boolean): void;
    stop(): void;
    createAnswer(): Promise<RTCSessionDescriptionInit>;
    setLocalDescription(sdp: RTCSessionDescriptionInit): Promise<void>;
    setRemoteDescription(sdp: RTCSessionDescriptionInit): Promise<void>;
    getInternalState<K extends keyof WebRTCInternalStateMap>(stateName: K): ServiceStateValue<WebRTCInternalStateMap, K>;
    getStats(selector?: MediaStreamTrack | null): Promise<RTCStatsReport | null>;
    isRemoteHeld(): boolean;
    isRemoteMute(): boolean;
    isStable(): boolean;
    getLocalDescription(): RTCSessionDescriptionInit | null;
    waitForIceGathering(): Promise<void>;
    private initialize;
    private startNewGathering;
    private changeInternalState;
    private updateAudioDirectionBeforeNegotiation;
    private updateAudioDirectionAfterNegotiation;
    private getAudioTransceivers;
    private updateAudioDirectionWithoutNegotiation;
    private createDataChannel;
    private endDataChannel;
    private initializeDataChannel;
    private sendP2PCommand;
    private isValidCommand;
    private getCommandFromDataChannelMessage;
    private onP2PCommand;
    private setRemoteMute;
    private updateMuteForRemote;
    private registerPeerEvents;
    private unregisterPeerEvents;
    private registerAudioLevelTracker;
    private unregisterAudioLevelTracker;
    private restartIce;
    private onIceCandidate;
    private onIceCandidateError;
    private onNegotiationNeeded;
    private onTrack;
    private onConnectionStateChange;
    private onIceConnectionStateChange;
    private onSignalingStateChange;
    private onIceGatheringStateChange;
    private loadInputTrack;
    private onIceGatheringComplete;
    private onDataChannel;
    private clearIceGatheringData;
    private clearIceGatheringWaiters;
}
//# sourceMappingURL=Processor.d.ts.map